name: Input Parameters playground

# configure manual trigger
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type such as 'snapshot', 'milestone' or 'release'
        required: true
        default: 'snapshot'
        type: string
      eclipse_profile:
        description: Eclipse Profile
        required: true
        default: 'e428'
        type: string
      skip_tests:
        description: skip ls tests execution
        required: false
        default: false
        type: boolean
      sts4-language-servers-version:
        description: version of sts4 ls extensions
        required: false
        type: string
      ref:
        description: Git branch, tag, commit hash
        required: false
        default: 'main'
        type: string

jobs:

  eclipse-language-servers-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Timestamp
        id: timestamp
        run: echo "name=date::$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
      - name: Cmd
        run: |
          p2_qualifier_param=""
          if ! [[ -z ${{ inputs.sts4-language-servers-version }} ]]; then
            p2_qualifier_param="-Dp2.qualifier=${{ inputs.sts4-language-servers-version }}"
          fi  
          echo "mvn clean package \
          -P${{ inputs.eclipse_profile }} \
          ${p2_qualifier_param} \
          -P${{ inputs.build_type }} -DskipTests=${{ inputs.skip_tests }} \
          -Dbuild.qualifier=${{ steps.timestamp.outputs.date }} \
          -Dtimestamp=${{ steps.date.outputs.date }}"
