name: Input Parameters playground

# configure manual trigger
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type such as 'snapshot', 'milestone' or 'release'
        required: true
        default: 'snapshot'
        type: string
      eclipse_profile:
        description: Eclipse Profile
        required: true
        default: 'e428'
        type: string
      skip_tests:
        description: skip ls tests execution
        required: false
        default: false
        type: boolean
      sts4-language-servers-version:
        description: version of sts4 ls extensions
        required: false
        type: string
      ref:
        description: Git branch, tag, commit hash
        required: false
        default: 'main'
        type: string

jobs:

  eclipse-language-servers-build:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
        id: timestamp
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Cmd
        run: |
          p2_qualifier=${{ inputs.sts4-language-servers-version }}
          p2_qualifier_param=""
          if ! [[ -z ${p2_qualifier} ]]; then
            p2_qualifier_param="-Dp2.qualifier=${p2_qualifier}"
          fi  
          echo "mvn clean package \
          -P${{ inputs.eclipse_profile }} \
          ${p2_qualifier_param} \
          -P${{ inputs.build_type }} -DskipTests=${{ inputs.skip_tests }} \
          -Dbuild.qualifier=${{ steps.timestamp.outputs.date }} \

  job-e427:
    runs-on: ubuntu-latest
    needs: [ eclipse-language-servers-build ]
    steps:
      - name: Cmd
        run: |
          echo "Stamp ${{ job.eclipse-language-servers-build.steps.timestamp.outputs.date }}

  job-e428:
    runs-on: ubuntu-latest
    needs: [ eclipse-language-servers-build ]
    steps:
      - name: Cmd
        run: |
          echo "Stamp ${{ job.eclipse-language-servers-build.steps.timestamp.outputs.date }}
