name: Next

on:
  workflow_run:
    workflows: ["Failure"]
    types: [completed]
    conclusion: "success"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run
        run: echo "Success!"
