name: Next

on:
  workflow_run:
    workflows: ["Failure"]
    types: [completed]
#    conclusion: 'success'
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
jobs:
if: ${{ github.event.workflow_run.conclusion == 'success' }}
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run
        run: echo "Success!"
